export const REGIONS_LOADING = 'REGIONS_LOADING';
export const ADD_REGIONS = 'ADD_REGION';
export const REGIONS_FAILED = 'REGIONS_FAILED';

export const REGIONS_HISTORY_LOADING = 'REGIONS_HISTORY_LOADING';
export const ADD_REGIONS_HISTORY = 'ADD_REGIONS_HISTORY';
export const REGIONS_HISTORY_FAILED = 'REGIONS_HISTORY_FAILED';

export const REGIONS_GEOGRAPHY_LOADING = 'REGIONS_GEOGRAPHY_LOADING';
export const ADD_REGIONS_GEOGRAPHY = 'ADD_REGIONS_GEOGRAPHY';
export const REGIONS_GEOGRAPHY_FAILED = 'REGIONS_GEOGRAPHY_FAILED';

export const ADD_REGIONS_COMMENTS = 'ADD_COMMENTS';
export const REGIONS_COMMENTS_FAILED = 'COMMENTS_FAILED';
export const ADD_REGION_COMMENT = 'ADD_REGION_COMMENT';

export const TOURS_LOADING = 'TOURS_LOADING';
export const ADD_TOURS = 'ADD_TOURS';
export const TOURS_FAILED = 'TOURS_FAILED';

export const CHARITIES_LOADING = 'CHARITIES_LOADING';
export const ADD_CHARITIES = 'ADD_CHARITIES';
export const CHARITIES_FAILED = 'CHARITIES_FAILED';

export const ADD_FAVORITE = 'ADD_FAVORITE';