export const COFFEES = [
    {
        id: 0,
        productNumber: '001',
        name: "Native Blend",
        region: "Colombia",
        attributes: ["bold", "strong", "rich"],
        description: "The best!",
        weight: 1,
        price: 12.99,
        donation: 2,
        image: "/assets/images/coffee-farmer.jpg",
    },
    {
        id: 1,
        productNumber: '002',
        name: "Local Roast",
        region: "Colombia",
        attributes: ["bold", "dark", "rich"],
        description: "The best!",
        weight: 1,
        price: 15.99,
        donation: 3,
        image: "/assets/images/coffee-farmer.jpg",
    },
    {
        id: 2,
        productNumber: '003',
        name: "Nearby Beans",
        region: "Colombia",
        attributes: ["smooth", "dark", "bitter"],
        description: "The best!",
        weight: 1,
        price: 11.99,
        donation: 2,
        image: "/assets/images/coffee-farmer.jpg",
    },
    {
        id: 3,
        productNumber: '004',
        name: "Talk of the Field",
        region: "Colombia",
        attributes: ["bold", "sweet", "rich"],
        description: "The best!",
        weight: 1,
        price: 10.99,
        donation: 2,
        image: "/assets/images/coffee-farmer.jpg",
    },
]

