export const COFFEES = [
    {
        id: 0,
        productNumber: '001',
        name: "Native Blend",
        region: "Colombia",
        attributes: ["bold", "strong", "rich"],
        description: "The best!",
        text:"Picked on the full moon. Freindly people grow this. It's such a treat to have this brew. You're gonna be helping out some great folks!",
        weight: 1,
        price: 12.99,
        donation: 2.00,
        image: "/assets/images/coffee-farmer.jpg",
    },
    {
        id: 1,
        productNumber: '002',
        name: "Local Roast",
        region: "Colombia",
        attributes: ["bold", "dark", "rich"],
        description: "The best!",
        text:"They got it right!!. For centuries people have been trying to grow the perfect bean. These folks have won the bean race!",
        weight: 1,
        price: 15.99,
        donation: 3.00,
        image: "/assets/images/coffee-farmer.jpg",
    },
    {
        id: 2,
        productNumber: '003',
        name: "Nearby Beans",
        region: "Colombia",
        attributes: ["smooth", "dark", "bitter"],
        description: "The best!",
        text:"How does it feel to have a cup straight from the source. I'll tell ya. It's magnificent!. These people care about the land, they care about their work and their family. They grow a mean bean!",
        weight: 1,
        price: 11.99,
        donation: 2.00,
        image: "/assets/images/coffee-farmer.jpg",
    },
    {
        id: 3,
        productNumber: '004',
        name: "Talk of the Field",
        region: "Colombia",
        attributes: ["bold", "sweet", "rich"],
        description: "The best!",
        text:"Are there any words to describe true perfection?. If you know of any, maybe you can write the description better than me. Absolutly, 'cat got your tounge', good!",
        weight: 1,
        price: 10.99,
        donation: 2.00,
        image: "/assets/images/coffee-farmer.jpg",
    },
]

