export const REGIONS_GEOGRAPHY = [
    {
        id: 0,
        name: 'Colombia',
        image: '../assets/images/coffee-farm-one.jpg',
        elevation: 1233,
        featured: false,
        description: "General Geography",
        content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit perferendis cum quasi iusto similique facere vel, nobis iste rem porro, quam at architecto quisquam earum animi hic iure, est placeat aperiam! Architecto dolorem commodi esse libero asperiores sapiente rem. Doloribus aspernatur qui id illum cum suscipit nisi repudiandae dicta a numquam, consequuntur eius accusantium accusamus temporibus, quam dignissimos ex aliquid aliquam aperiam unde tempore veritatis? Aliquam similique sapiente numquam obcaecati aliquid eos architecto vel et modi, asperiores laborum alias amet? Aliquid fugit temporibus assumenda deleniti sint debitis asperiores expedita aperiam accusamus doloremque mollitia aspernatur dolorum accusantium, omnis ipsa quia numquam odio excepturi at amet nulla labore saepe fuga? Suscipit, autem ratione! Fugiat officia beatae tenetur doloribus ex mollitia veritatis distinctio optio quaerat sequi. Assumenda quos libero voluptatum soluta quaerat est aperiam praesentium quidem porro, non, accusantium cupiditate sapiente, dicta neque vero incidunt corrupti aspernatur. Est dolore aperiam commodi placeat consequatur repellendus numquam! Ducimus hic dolore minima consequatur pariatur voluptates perferendis, obcaecati dolores unde optio, eum doloremque! Velit, quas libero? In magni animi, fuga ullam aliquid suscipit earum eaque voluptate aut, architecto assumenda a ut natus doloremque voluptas adipisci obcaecati. Eaque error numquam perferendis voluptatibus sit atque ullam harum quae enim",
    },
    {
        id: 1,
        name:'Ethiopia',
        image: '../assets/images/coffee-farm-one.jpg',
        elevation: 877,
        featured: false,
        description: "General Geography",
        content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit perferendis cum quasi iusto similique facere vel, nobis iste rem porro, quam at architecto quisquam earum animi hic iure, est placeat aperiam! Architecto dolorem commodi esse libero asperiores sapiente rem. Doloribus aspernatur qui id illum cum suscipit nisi repudiandae dicta a numquam, consequuntur eius accusantium accusamus temporibus, quam dignissimos ex aliquid aliquam aperiam unde tempore veritatis? Aliquam similique sapiente numquam obcaecati aliquid eos architecto vel et modi, asperiores laborum alias amet? Aliquid fugit temporibus assumenda deleniti sint debitis asperiores expedita aperiam accusamus doloremque mollitia aspernatur dolorum accusantium, omnis ipsa quia numquam odio excepturi at amet nulla labore saepe fuga? Suscipit, autem ratione! Fugiat officia beatae tenetur doloribus ex mollitia veritatis distinctio optio quaerat sequi. Assumenda quos libero voluptatum soluta quaerat est aperiam praesentium quidem porro, non, accusantium cupiditate sapiente, dicta neque vero incidunt corrupti aspernatur. Est dolore aperiam commodi placeat consequatur repellendus numquam! Ducimus hic dolore minima consequatur pariatur voluptates perferendis, obcaecati dolores unde optio, eum doloremque! Velit, quas libero? In magni animi, fuga ullam aliquid suscipit earum eaque voluptate aut, architecto assumenda a ut natus doloremque voluptas adipisci obcaecati. Eaque error numquam perferendis voluptatibus sit atque ullam harum quae enim"
    },
    {
        id: 2,
        name:'Kenya',
        image: '../../assets/images/coffee-farm-one.jpg',
        elevation: 2901,
        featured: false,
        description: "General Geography",
        content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit perferendis cum quasi iusto similique facere vel, nobis iste rem porro, quam at architecto quisquam earum animi hic iure, est placeat aperiam! Architecto dolorem commodi esse libero asperiores sapiente rem. Doloribus aspernatur qui id illum cum suscipit nisi repudiandae dicta a numquam, consequuntur eius accusantium accusamus temporibus, quam dignissimos ex aliquid aliquam aperiam unde tempore veritatis? Aliquam similique sapiente numquam obcaecati aliquid eos architecto vel et modi, asperiores laborum alias amet? Aliquid fugit temporibus assumenda deleniti sint debitis asperiores expedita aperiam accusamus doloremque mollitia aspernatur dolorum accusantium, omnis ipsa quia numquam odio excepturi at amet nulla labore saepe fuga? Suscipit, autem ratione! Fugiat officia beatae tenetur doloribus ex mollitia veritatis distinctio optio quaerat sequi. Assumenda quos libero voluptatum soluta quaerat est aperiam praesentium quidem porro, non, accusantium cupiditate sapiente, dicta neque vero incidunt corrupti aspernatur. Est dolore aperiam commodi placeat consequatur repellendus numquam! Ducimus hic dolore minima consequatur pariatur voluptates perferendis, obcaecati dolores unde optio, eum doloremque! Velit, quas libero? In magni animi, fuga ullam aliquid suscipit earum eaque voluptate aut, architecto assumenda a ut natus doloremque voluptas adipisci obcaecati. Eaque error numquam perferendis voluptatibus sit atque ullam harum quae enim"
    },
    {
        id: 3,
        name:'Costa Rica',
        image: '../assets/images/coffee-farm-one.jpg',
        elevation: 42,
        featured: true,
        description: "General Geography",
        content:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit perferendis cum quasi iusto similique facere vel, nobis iste rem porro, quam at architecto quisquam earum animi hic iure, est placeat aperiam! Architecto dolorem commodi esse libero asperiores sapiente rem. Doloribus aspernatur qui id illum cum suscipit nisi repudiandae dicta a numquam, consequuntur eius accusantium accusamus temporibus, quam dignissimos ex aliquid aliquam aperiam unde tempore veritatis? Aliquam similique sapiente numquam obcaecati aliquid eos architecto vel et modi, asperiores laborum alias amet? Aliquid fugit temporibus assumenda deleniti sint debitis asperiores expedita aperiam accusamus doloremque mollitia aspernatur dolorum accusantium, omnis ipsa quia numquam odio excepturi at amet nulla labore saepe fuga? Suscipit, autem ratione! Fugiat officia beatae tenetur doloribus ex mollitia veritatis distinctio optio quaerat sequi. Assumenda quos libero voluptatum soluta quaerat est aperiam praesentium quidem porro, non, accusantium cupiditate sapiente, dicta neque vero incidunt corrupti aspernatur. Est dolore aperiam commodi placeat consequatur repellendus numquam! Ducimus hic dolore minima consequatur pariatur voluptates perferendis, obcaecati dolores unde optio, eum doloremque! Velit, quas libero? In magni animi, fuga ullam aliquid suscipit earum eaque voluptate aut, architecto assumenda a ut natus doloremque voluptas adipisci obcaecati. Eaque error numquam perferendis voluptatibus sit atque ullam harum quae enim"
    },
    {
        id: 4,
        name:'Colombia',
        image: '../assets/images/coffee-farm-one.jpg',
        elevation: 877,
        featured: false,
        description: "The Mountains",
        content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit perferendis cum quasi iusto similique facere vel, nobis iste rem porro, quam at architecto quisquam earum animi hic iure, est placeat aperiam! Architecto dolorem commodi esse libero asperiores sapiente rem. Doloribus aspernatur qui id illum cum suscipit nisi repudiandae dicta a numquam, consequuntur eius accusantium accusamus temporibus, quam dignissimos ex aliquid aliquam aperiam unde tempore veritatis? Aliquam similique sapiente numquam obcaecati aliquid eos architecto vel et modi, asperiores laborum alias amet? Aliquid fugit temporibus assumenda deleniti sint debitis asperiores expedita aperiam accusamus doloremque mollitia aspernatur dolorum accusantium, omnis ipsa quia numquam odio excepturi at amet nulla labore saepe fuga? Suscipit, autem ratione! Fugiat officia beatae tenetur doloribus ex mollitia veritatis distinctio optio quaerat sequi. Assumenda quos libero voluptatum soluta quaerat est aperiam praesentium quidem porro, non, accusantium cupiditate sapiente, dicta neque vero incidunt corrupti aspernatur. Est dolore aperiam commodi placeat consequatur repellendus numquam! Ducimus hic dolore minima consequatur pariatur voluptates perferendis, obcaecati dolores unde optio, eum doloremque! Velit, quas libero? In magni animi, fuga ullam aliquid suscipit earum eaque voluptate aut, architecto assumenda a ut natus doloremque voluptas adipisci obcaecati. Eaque error numquam perferendis voluptatibus sit atque ullam harum quae enim",
    },
    {
        id: 5,
        name:'Colombia',
        image: '../assets/images/coffee-farm-one.jpg',
        elevation: 877,
        featured: false,
        description: "The Coast",
        content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit perferendis cum quasi iusto similique facere vel, nobis iste rem porro, quam at architecto quisquam earum animi hic iure, est placeat aperiam! Architecto dolorem commodi esse libero asperiores sapiente rem. Doloribus aspernatur qui id illum cum suscipit nisi repudiandae dicta a numquam, consequuntur eius accusantium accusamus temporibus, quam dignissimos ex aliquid aliquam aperiam unde tempore veritatis? Aliquam similique sapiente numquam obcaecati aliquid eos architecto vel et modi, asperiores laborum alias amet? Aliquid fugit temporibus assumenda deleniti sint debitis asperiores expedita aperiam accusamus doloremque mollitia aspernatur dolorum accusantium, omnis ipsa quia numquam odio excepturi at amet nulla labore saepe fuga? Suscipit, autem ratione! Fugiat officia beatae tenetur doloribus ex mollitia veritatis distinctio optio quaerat sequi. Assumenda quos libero voluptatum soluta quaerat est aperiam praesentium quidem porro, non, accusantium cupiditate sapiente, dicta neque vero incidunt corrupti aspernatur. Est dolore aperiam commodi placeat consequatur repellendus numquam! Ducimus hic dolore minima consequatur pariatur voluptates perferendis, obcaecati dolores unde optio, eum doloremque! Velit, quas libero? In magni animi, fuga ullam aliquid suscipit earum eaque voluptate aut, architecto assumenda a ut natus doloremque voluptas adipisci obcaecati. Eaque error numquam perferendis voluptatibus sit atque ullam harum quae enim",
    },
    {
        id: 6,
        name:'Colombia',
        image: '../assets/images/coffee-farm-one.jpg',
        elevation: 877,
        featured: false,
        description: "The Current State Colombia",
        content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit perferendis cum quasi iusto similique facere vel, nobis iste rem porro, quam at architecto quisquam earum animi hic iure, est placeat aperiam! Architecto dolorem commodi esse libero asperiores sapiente rem. Doloribus aspernatur qui id illum cum suscipit nisi repudiandae dicta a numquam, consequuntur eius accusantium accusamus temporibus, quam dignissimos ex aliquid aliquam aperiam unde tempore veritatis? Aliquam similique sapiente numquam obcaecati aliquid eos architecto vel et modi, asperiores laborum alias amet? Aliquid fugit temporibus assumenda deleniti sint debitis asperiores expedita aperiam accusamus doloremque mollitia aspernatur dolorum accusantium, omnis ipsa quia numquam odio excepturi at amet nulla labore saepe fuga? Suscipit, autem ratione! Fugiat officia beatae tenetur doloribus ex mollitia veritatis distinctio optio quaerat sequi. Assumenda quos libero voluptatum soluta quaerat est aperiam praesentium quidem porro, non, accusantium cupiditate sapiente, dicta neque vero incidunt corrupti aspernatur. Est dolore aperiam commodi placeat consequatur repellendus numquam! Ducimus hic dolore minima consequatur pariatur voluptates perferendis, obcaecati dolores unde optio, eum doloremque! Velit, quas libero? In magni animi, fuga ullam aliquid suscipit earum eaque voluptate aut, architecto assumenda a ut natus doloremque voluptas adipisci obcaecati. Eaque error numquam perferendis voluptatibus sit atque ullam harum quae enim",
    },
];