export const REGIONS = [
    {
        id: 0,
        name: 'Colombia',
        image: '../assets/images/colombia-farm.jpg',
        elevation: 1233,
        featured: false,
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit, voluptate optio.  ",
        region: "Colombia",
    },
    {
        id: 1,
        name:'Ethiopia',
        image: '../assets/images/coffee-farmer.jpg',
        elevation: 877,
        featured: false,
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit, voluptate opti ",
        region: "Ethiopia",
    },
    {
        id: 2,
        name:'Kenya',
        image: '../assets/images/coffee-farm-one.jpg',
        elevation: 2901,
        featured: false,
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit, voluptate optio.",
        region: "Kenya",
    },
    {
        id: 3,
        name:'Costa Rica',
        image: '../assets/images/lady-picks-coffee.jpg',
        elevation: 42,
        featured: true,
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit, voluptate optio.",
        region: "Costa Rica",
    },
    {
        id: 4,
        name:'Test Land',
        image: '../assets/images/lady-picks-coffee.jpg',
        elevation: 42,
        featured: true,
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit, voluptate optio.",
    }
];